# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1216f0b3ad9b2dd3d0cb25d497c820bb6fbd4391e87d2decaf0957eaf7b565f82017010776e5252c3300371aa820cbdaee927a8fc4e212069fae626c59c655cd

test:
  secret_key_base: 236d61f44ee4de2ae08b192b43d7f4193aaf6c249018e2d3732a5010c740c490252169ff3197cf8696508df0df607abb866af06f408691841a3ebde75e823d21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
